# Generated by Django 4.2.5 on 2023-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0004_alter_writer_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='userImage',
            field=models.ImageField(default='blog/user/default_user.png', upload_to='blog/user'),
        ),
    ]
