# Generated by Django 4.1.13 on 2024-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_alter_writer_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='userImage',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
