# Generated by Django 4.1.13 on 2024-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0006_alter_writer_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='userImage',
            field=models.CharField(default='/static/userimg/default_user.png', max_length=1000),
        ),
    ]
