# Generated by Django 4.2.5 on 2023-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='parentSno',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
