# Generated by Django 4.2.5 on 2023-11-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_parentsno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='parentSno',
            field=models.IntegerField(null=True),
        ),
    ]
