# Generated by Django 4.2.5 on 2023-11-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_parentsno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parentSno',
        ),
    ]
