# Generated by Django 4.1.13 on 2024-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
